import { Routes, Route, Navigate } from 'react-router-dom';
import Landing from './pages/Landing';
import Dashboard from './pages/Dashboard';
import Auth from './pages/Auth';
import MarketRegime from './pages/MarketRegime';
import Top500 from './pages/Top500';
import Login from './pages/Login';
import Register from './pages/Register';
import Pricing from './pages/Pricing';
import Watchlist from './pages/Watchlist';
import DailyTop10 from './pages/DailyTop10';